# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='date due')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('assignment_date', models.DateTimeField(verbose_name='date assigned')),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listitems.Task'),
        ),
    ]
